Fixed pipeline

diff --git a/.github/workflows/publish_to_pypi.yml b/.github/workflows/publish_to_pypi.yml
--- a/.github/workflows/publish_to_pypi.yml
+++ b/.github/workflows/publish_to_pypi.yml
@@ -33,27 +33,27 @@ jobs:
           packageLocalVersion=$(python -c 'from version import version; print(version)')
           echo "localVersion=$packageLocalVersion" >> $GITHUB_ENV
 
-      - name: Fetch remote package version
-        run: |
-          packageRemoteVersion=$(python -c "
-          import pkg_resources 
-          try:
-            print(pkg_resources.get_distribution('osw-incline').version)
-          except pkg_resources.DistributionNotFound:
-            print('0.0.0')
-          ")
-          echo "remoteVersion=$packageRemoteVersion" >> $GITHUB_ENV
-
-      - name: Printing local and remote versions
-        run: echo "Local version ${{env.localVersion}} and remote version ${{env.remoteVersion}}"
-
-      - name: Compare local and remote versions
-        run: |
-          echo "Comparing versions..."
-          if dpkg --compare-versions ${{env.localVersion}} "le" ${{env.remoteVersion}}; then
-            echo "The remote version (${{env.remoteVersion}}) is greater than or equal to the local version (${{env.localVersion}}). Aborting deployment."
-            exit 1
-          fi
+#      - name: Fetch remote package version
+#        run: |
+#          packageRemoteVersion=$(python -c "
+#          import pkg_resources
+#          try:
+#            print(pkg_resources.get_distribution('osw-incline').version)
+#          except pkg_resources.DistributionNotFound:
+#            print('0.0.0')
+#          ")
+#          echo "remoteVersion=$packageRemoteVersion" >> $GITHUB_ENV
+#
+#      - name: Printing local and remote versions
+#        run: echo "Local version ${{env.localVersion}} and remote version ${{env.remoteVersion}}"
+#
+#      - name: Compare local and remote versions
+#        run: |
+#          echo "Comparing versions..."
+#          if dpkg --compare-versions ${{env.localVersion}} "le" ${{env.remoteVersion}}; then
+#            echo "The remote version (${{env.remoteVersion}}) is greater than or equal to the local version (${{env.localVersion}}). Aborting deployment."
+#            exit 1
+#          fi
 
       - name: Setup python wheel
         run: pip install wheel
